### ISSUE TITLE
inference.py error

### ISSUE THREAD

**Issue by seekingdeep** [liuch37/pan-pytorch#10]
Hello,
When running inference.py i get error:
```
(mmocr) home@home-lnx:~/programs/pan-pytorch$ python inference.py --input ./mytest/ --output ./results --model ./outputs/model_epoch_20.pth --bbox_type poly
Namespace(bbox_type='poly', gpu=False, input='./mytest/', model='./outputs/model_epoch_20.pth', output='./results', worker=4)
CPU being used!
Create dataset......
Length of test dataset is: 1
Create model......
Prediction on testset......
Testing 0/1
/home/home/anaconda3/envs/mmocr/lib/python3.7/site-packages/torch/nn/functional.py:2973: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "inference.py", line 114, in <module>
    det_res = get_results(det_out, data['img_metas'], min_area, min_score, bbox_type)
  File "/home/home/programs/pan-pytorch/utils/helper.py", line 55, in get_results
    label = cv2.resize(label, (img_size[1], img_size[0]), interpolation=cv2.INTER_NEAREST)
cv2.error: OpenCV(4.5.2) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - Can't parse 'dsize'. Sequence item with index 0 has a wrong type
>  - Can't parse 'dsize'. Sequence item with index 0 has a wrong type
```

**Comment by seekingdeep** [comment]
alright, i was able to solve the issue by installing an older version of opencv:
```
pip install opencv-python==4.5.1.48
```

**Comment by aswa123** [comment]
@seekingdeep how you solved this this i can't.
