### ISSUE TITLE
SROIE dataset error

### ISSUE THREAD

**Issue by seekingdeep** [liuch37/pan-pytorch#12]
Hi there,
i am trying to train the [SROIE dataset](https://rrc.cvc.uab.es/?ch=13), so i used the ctw1500 config in training, basically i replaced the ctw1500 images and annotations with the SROIE images and annotations, but i am getting an error when trying to train:
```
(mmocr) home@home-lnx:~/programs/pan-pytorch$ python train.py --batch 4 --epoch 100 --dataset_type ctw --gpu True
Namespace(batch=4, dataset_type='ctw', epoch=100, gpu=True, model='', output='outputs', worker=4)
Random Seed: 5153
GPU being used!
Create dataset......
Length of train dataset is: 525
Create model......
Training starts......
Epoch: [1 | 100]
Traceback (most recent call last):
  File "train.py", line 183, in <module>
    for iter, data in enumerate(train_dataloader):
  File "/home/home/anaconda3/envs/mmocr/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/home/anaconda3/envs/mmocr/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/home/anaconda3/envs/mmocr/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/home/anaconda3/envs/mmocr/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/home/anaconda3/envs/mmocr/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/home/anaconda3/envs/mmocr/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/home/anaconda3/envs/mmocr/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/home/programs/pan-pytorch/dataset/ctw1500.py", line 358, in __getitem__
    return self.prepare_train_data(index)
  File "/home/home/programs/pan-pytorch/dataset/ctw1500.py", line 258, in prepare_train_data
    bboxes, words = get_ann(img, gt_path)
  File "/home/home/programs/pan-pytorch/dataset/ctw1500.py", line 49, in get_ann
    bbox = [np.int(gt[i]) for i in range(4, 32)]
  File "/home/home/programs/pan-pytorch/dataset/ctw1500.py", line 49, in <listcomp>
    bbox = [np.int(gt[i]) for i in range(4, 32)]
IndexError: list index out of range
```

**Comment by liuch37** [comment]
You need to make sure your new annotation files should have exact same format as ctw1500. Note ctw1500 label has 14 points for one polygon.

**Comment by seekingdeep** [comment]
the SROIE dataset is in the exact same format, though the SROIE have only 4 points
x1,y1,....x4,y4

**Comment by liuch37** [comment]
My ctw1500 only supports 14 point format. You can try to use 'ic15' which is for ICDAR2015 dataset, that should be closed to your ICDAR2019 dataset.

**Comment by seekingdeep** [comment]
Can't i train a new ctw1500 model with a dataset that have less than 14 points?
I have tested training the SROIE dataset using the ic15 configuration, but i am getting an error:
```
(mmocr) home@home-lnx:~/programs/pan-pytorch$ python train.py --batch 4 --epoch 5000 --dataset_type ic15 --gpu True
Namespace(batch=4, dataset_type='ic15', epoch=5000, gpu=True, model='', output='outputs', worker=4)
Random Seed: 2202
GPU being used!
Create dataset......
Length of train dataset is: 526
Create model......
Training starts......
Epoch: [1 | 5000]
Traceback (most recent call last):
  File "train.py", line 183, in <module>
    for iter, data in enumerate(train_dataloader):
  File "/home/home/anaconda3/envs/mmocr/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/home/anaconda3/envs/mmocr/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/home/anaconda3/envs/mmocr/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/home/anaconda3/envs/mmocr/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/home/anaconda3/envs/mmocr/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/home/anaconda3/envs/mmocr/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/home/anaconda3/envs/mmocr/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/home/programs/pan-pytorch/dataset/ic15.py", line 438, in __getitem__
    return self.prepare_train_data(index)
  File "/home/home/programs/pan-pytorch/dataset/ic15.py", line 309, in prepare_train_data
    bboxes, words = get_ann(img, gt_path)
  File "/home/home/programs/pan-pytorch/dataset/ic15.py", line 49, in get_ann
    word = gt[8].replace('\r', '').replace('\n', '')
IndexError: list index out of range
```

**Comment by liuch37** [comment]
You have to modify data loader yourself to support less than 14 points labeling. For the error, you need to check why gt is out of range.

**Comment by seekingdeep** [comment]
Thanks
