### ISSUE TITLE
Training fails when adding labels with 14 points

### ISSUE THREAD

**Issue by seekingdeep** [liuch37/pan-pytorch#15]
@liuch37 
i am trying to train using the following [example.zip](https://github.com/liuch37/pan-pytorch/files/6542009/example.zip), but i get error, eventhough the labels are 14 points.

```
(mmocr) home@home-lnx:~/programs/pan-pytorch$ python train.py --batch 1 --epoch 100 --dataset_type ctw --gpu True
Namespace(batch=1, dataset_type='ctw', epoch=100, gpu=True, model='', output='outputs', worker=4)
Random Seed: 408
GPU being used!
Create dataset......
Length of train dataset is: 1
Create model......
Training starts......
Epoch: [1 | 100]
Traceback (most recent call last):
  File "train.py", line 183, in <module>
    for iter, data in enumerate(train_dataloader):
  File "/home/home/anaconda3/envs/mmocr/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/home/anaconda3/envs/mmocr/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/home/anaconda3/envs/mmocr/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/home/anaconda3/envs/mmocr/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/home/anaconda3/envs/mmocr/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/home/anaconda3/envs/mmocr/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/home/anaconda3/envs/mmocr/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/home/programs/pan-pytorch/dataset/ctw1500.py", line 358, in __getitem__
    return self.prepare_train_data(index)
  File "/home/home/programs/pan-pytorch/dataset/ctw1500.py", line 258, in prepare_train_data
    bboxes, words = get_ann(img, gt_path)
  File "/home/home/programs/pan-pytorch/dataset/ctw1500.py", line 49, in get_ann
    bbox = [np.int(gt[i]) for i in range(4, 32)]
  File "/home/home/programs/pan-pytorch/dataset/ctw1500.py", line 49, in <listcomp>
    bbox = [np.int(gt[i]) for i in range(4, 32)]
IndexError: list index out of range

```

**Comment by liuch37** [comment]
You need to check the exact ctw label protocol for each line https://github.com/Yuliang-Liu/Curve-Text-Detector/tree/master/data.

**Comment by seekingdeep** [comment]
i created the [example.zip](https://github.com/liuch37/pan-pytorch/files/6542009/example.zip) using the official ctw1500 [labeling tool](https://github.com/Yuliang-Liu/Curve-Text-Detector/tree/master/data#labeling-tool)

**Comment by liuch37** [comment]
You only have 28 values per line, by mine have 32 values. I am following the format in the link (https://1drv.ms/u/s!Aplwt7jiPGKilH4XzZPoKrO7Aulk) (OneDrive)
