### ISSUE TITLE
Inference.py Error

### ISSUE THREAD

**Issue by aswa123** [liuch37/pan-pytorch#17]
(lib) swap@pop-os:~/Downloads/pan-pytorch-master$ python inference.py --input ./data/MSRA-TD500/test --model ./outputs/model_epoch_0.pth --bbox_type poly

Namespace(bbox_type='poly', gpu=False, input='./data/MSRA-TD500/test', model='./outputs/model_epoch_0.pth', output='results', worker=4)
CPU being used!
Create dataset......
Length of test dataset is: 400
Create model......
Prediction on testset......
./data/MSRA-TD500/test/IMG_0507.gt
./data/MSRA-TD500/test/IMG_1732.gt
./data/MSRA-TD500/test/IMG_2106.gt
./data/MSRA-TD500/test/IMG_1722.gt
Traceback (most recent call last):
  File "inference.py", line 104, in <module>
    for idx, data in enumerate(test_dataloader):
  File "/home/swap/miniconda3/envs/lib/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/swap/miniconda3/envs/lib/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/swap/miniconda3/envs/lib/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/swap/miniconda3/envs/lib/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/swap/miniconda3/envs/lib/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/swap/miniconda3/envs/lib/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/swap/miniconda3/envs/lib/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/swap/Downloads/pan-pytorch-master/dataset/testdataset.py", line 79, in __getitem__
    return self.prepare_test_data(index)
  File "/home/swap/Downloads/pan-pytorch-master/dataset/testdataset.py", line 58, in prepare_test_data
    img = get_img(img_path)
  File "/home/swap/Downloads/pan-pytorch-master/dataset/testdataset.py", line 15, in get_img
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.3) /tmp/pip-req-build-l1r0y34w/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by aswa123** [comment]
Hello 
Thank you for your wonderful work.
but I got some error in inference.py 
can you please help me to solve this.

**Comment by liuch37** [comment]
This error happened because the image didn't load properly. Check if the current loaded image is empty or with problem.

**Comment by aswa123** [comment]
what so you mean didn't load properly
